apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gatemaster
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 400Mi
              cpu: 400m
          image: umg100/api-gateway:4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env: 
            - name: PORT
              value: "8081"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: AUTH_URL
              value: "auth-service.gatemaster.svc.cluster.local"
            - name: SERVICE_CRM_URL
              value: "crm.gatemaster.svc.cluster.local"
            - name: SERVICE_GATEMASTER_URL
              value: "gatemaster.gatemaster.svc.cluster.local"

