apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gatemaster
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 400Mi
              cpu: 400m
          image: umg100/api-gateway:tagname:4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env: 
            - PORT=8081
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - AUTH_URL=auth-service.gatemaster.svc.cluster.local
            - SERVICE_CRM_URL=crm.gatemaster.svc.cluster.local
            - SERVICE_GATEMASTER_URL=gatemaster.gatemaster.svc.cluster.local