apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: api-gateway
  namespace: flux-system
spec:
  image: umg100/api-gateway
  secretRef:
    name: dockerhub-credentials
  interval: 1m1s