apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: api-gateway
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: api-gateway
  policy:
    numerical:
      order: asc