apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - pgadmin-namespace.yaml
  - pgadmin-chart.yaml
configMapGenerator:
  - name: pgadmin-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml