apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
spec:
  releaseName: pgadmin4
  chart:
    spec:
      version: "1.27.0"
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: pgadmin-values