apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - redis-namespace.yaml
  - redis-chart.yaml
  - service-nodeport.yaml
configMapGenerator:
  - name: redis-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
  