apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      version: "19.6.4"
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: redis-values