apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 30000  # Puerto externo entre 30000-32767
  selector:
    app: redis-master