apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm
  namespace: gatemaster
spec:
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
        - name: crm
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 100m
          image: umg100/crm:5 # {"$imagepolicy": "flux-system:crm"}
          ports:
            - containerPort: 8090