apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatemaster
  namespace: gatemaster
spec:
  selector:
    matchLabels:
      app: gatemaster
  template:
    metadata:
      labels:
        app: gatemaster
    spec:
      containers:
        - name: gatemaster
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 100m
          image: umg100/gatemaster:1 # {"$imagepolicy": "flux-system:gatemaster"}
          ports:
            - containerPort: 8091