apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql
resources:
  - postgresql-namespace.yaml
  - postgresql-chart.yaml
configMapGenerator:
  - name: postgresql-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml