apiVersion: v1
kind: Service
metadata:
  name: pong-server-service
spec:
  type: NodePort  
  selector:
    app: pong-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
