apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - godaddy-webhook-chart.yaml
configMapGenerator:
  - name: godaddy-webhook-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml