apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatemaster-app
  namespace: gatemaster
  labels:
    app: gatemaster-app
spec:
  selector:
    matchLabels:
      app: gatemaster-app
  replicas: 2
  template:
    metadata:
      name: gatemaster-app
      labels:
        app: gatemaster-app
    spec:
      containers:
        - name: gatemaster-app
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 100m
          image: umg100/gatemaster:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          env: 
            - name: PORT
              value: "8091"
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_HOST
              value: "postgresql.postgresql.svc.cluster.local"
            - name: POSTGRES_DB
              value: "gatemaster"
            - name: POSTGRES_PASSWORD
              value: "1a7e52f0fcdd49078978051421df87cf"
            - name: POSTGRES_PORT
              value: "5432"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak.keycloak.svc.cluster.local"