apiVersion: v1
kind: Service
metadata:
  name: gatemaster-app
  namespace: gatemaster
spec:
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app: gatemaster-app
  type: ClusterIP