apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: gatemaster
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 100m
          image: umg100/auth-service:6 # {"$imagepolicy": "flux-system:auth-service"}
          ports:
            - containerPort: 8083