apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: gatemaster
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 2
  template:
    metadata:
      name: auth-service
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 100m
          image: umg100/auth-service:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env: 
            - name: PORT
              value: "8083"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak.keycloak.svc.cluster.local"
            - name: KEYCLOAK_REALM
              value: "master"
            - name: KEYCLOAK_CLIENT_ID
              value: "gatemaster"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "CHoY7OAqJ4j4JTut3AkPsCQtcRQKvcbF"
