apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: auth-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auth-service
  policy:
    numerical:
      order: asc