apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: flux-system
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ1bWcxMDAiOnsidXNlcm5hbWUiOiJ1bWcxMDAiLCJwYXNzd29yZCI6IlhmYjdmI1hRISE3UWY4UyIsImVtYWlsIjoic2VtaW5hcmlvMjAyNC51bWdAZ21haWwuY29tIiwiYXV0aCI6ImRXMW5NVEF3T2xobVlqZG1JMWhSSVNFM1VXWTRVdz09In19fQo=
type: kubernetes.io/dockerconfigjson