apiVersion: v1
kind: Secret
metadata:
  name: cert-manager
  namespace: cert-manager
type: Opaque
data:
  token: aDFlTTlVbUJhaXdrX0VpWDY2emZGU3dkeDJpaXM5VUFkSFc6UDZISGZhb3B1aG9VYlMyMnc3YzY4VQ== # "this-is-my-token" en Base64