apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: seminario2024.umg@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
        - 'gatemaster.online'
      dns01:
        webhook:
          config:
            apiKeySecretRef:
              name: cert-manager
              key: token
            production: true
            ttl: 600
          groupName: acme.gatemaster.online
          solverName: godaddy