apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-gatemaster-online
  namespace: cert-manager
spec:
  dnsNames:
  - '*.gatemaster.online'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: star-gatemaster-online
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "true"