apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager-chart.yaml
configMapGenerator:
- name: cert-manager-values
  files:
  - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
  