apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - godaddy-webhook
  - certificates
  - ingress-nginx
  - dockerhub-secret
  - redis
  - postgresql
  - pgadmin