apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - keycloak-namespace.yaml
  - keycloak-chart.yaml
configMapGenerator:
  - name: keycloak-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml